// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvdRyr41B4-tl4q2Scda1Q4kZaCBu-09g',
    appId: '1:333189456537:web:bb31cd2820a5d0a8734e08',
    messagingSenderId: '333189456537',
    projectId: 'square-d15d6',
    authDomain: 'square-d15d6.firebaseapp.com',
    storageBucket: 'square-d15d6.appspot.com',
    measurementId: 'G-PZPJG8H0E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnqO7fXukulAyWP6gnCa9TRAeqbFVH0V4',
    appId: '1:333189456537:android:17d4037f7a88c794734e08',
    messagingSenderId: '333189456537',
    projectId: 'square-d15d6',
    storageBucket: 'square-d15d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWA0nK86sbkk8-LHSKGE-icM95X2VwGak',
    appId: '1:333189456537:ios:4fbe41ef67c1c8b4734e08',
    messagingSenderId: '333189456537',
    projectId: 'square-d15d6',
    storageBucket: 'square-d15d6.appspot.com',
    iosClientId:
        '333189456537-69tkaput3b4qiead7dnte0fje0etf5sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.square',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWA0nK86sbkk8-LHSKGE-icM95X2VwGak',
    appId: '1:333189456537:ios:4fbe41ef67c1c8b4734e08',
    messagingSenderId: '333189456537',
    projectId: 'square-d15d6',
    storageBucket: 'square-d15d6.appspot.com',
    iosClientId:
        '333189456537-69tkaput3b4qiead7dnte0fje0etf5sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.square',
  );
}
