platform :android do
  lane :closed_beta do
    begin
      gradle(task: "clean")
      gradle(
        task: "bundle",
        build_type: 'Release'
      )
      sh("firebase appdistribution:distribute --release-notes 'New release' --apk app/build/outputs/apk/release/app-release.apk")
    end
  end
end
